### ISSUE TITLE
README中轴承数量有误

### ISSUE THREAD

**Issue by OYCN** [peng-zhihui/CycloidAcuratorNano#3]
是不是轴承数量有误：6705x2, MR106 x **2**,  MR74 x **13**

**Comment by cacazjj** [comment]
从设计图中看没有问题，是正确的。一共两个摆线碟，一个摆线碟使用一个MR106（中心）、六个MR74（环绕），两个6705，还有一个MR74是用在偏心轴上的。

**Comment by OYCN** [comment]
> 从设计图中看没有问题，是正确的。一共两个摆线碟，一个摆线碟使用一个MR106（中心）、六个MR74（环绕），两个6705，还有一个MR74是用在偏心轴上的。

我的描述有误，README中的轴承数量描述有误，我更改一下标题

**Comment by cacazjj** [comment]
> > 从设计图中看没有问题，是正确的。一共两个摆线碟，一个摆线碟使用一个MR106（中心）、六个MR74（环绕），两个6705，还有一个MR74是用在偏心轴上的。
> 
> 我的描述有误，README中的轴承数量描述有误，我更改一下标题

README中的描述确实错了。MR106轴承是2个，MR74是13个。我买了14个MR106。😓

**Comment by peng-zhihui** [comment]
打错了，已修改
